# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toyrobot_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_cord', models.FloatField()),
                ('y_cord', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='robot',
            name='dirs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyrobot_api.Direction'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyrobot_api.Table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_l',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_l', to='toyrobot_api.Coordinates'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_r', to='toyrobot_api.Coordinates'),
        ),
    ]
