# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toyrobot_api', '0003_auto_20160312_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='dirs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='toyrobot_api.Direction'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='toyrobot_api.Table'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='x_cord',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='y_cord',
            field=models.FloatField(null=True),
        ),
    ]
